# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_BATTERY_DETECT)   += charger-monitor-v3.o
obj-$(CONFIG_BQ25890_SLAVE_CHARGER) += bq24192_slave_charger.o bq25890_slave_charger.o bq25601d_slave_charger.o
obj-$(CONFIG_QPNP_SMB5)			+= step-chg-jeita.o vivo-battery.o vivo-qpnp-smb5.o vivo-smb5-lib.o pmic-voter.o storm-watch.o schgm-flash.o
obj-$(CONFIG_SMB1390_CHARGE_PUMP_PSY)	+= smb1390-charger-psy.o pmic-voter.o
obj-$(CONFIG_SMB1355_SLAVE_CHARGER)	+= smb1355-charger.o pmic-voter.o
obj-$(CONFIG_QPNP_QNOVO5)		+= qpnp-qnovo5.o battery.o pmic-voter.o
obj-$(CONFIG_QPNP_FG_GEN4)		+= qpnp-fg-gen4.o fg-memif.o fg-util.o fg-alg.o pmic-voter.o
obj-$(CONFIG_QPNP_QG)			+= vivo-qpnp-qg.o pmic-voter.o qg-util.o vivo-qg-soc.o qg-sdam.o qg-battery-profile.o qg-profile-lib.o fg-alg.o
obj-$(CONFIG_HL6111R)			+= hl6111r.o
obj-$(CONFIG_SMB1398_CHARGER)		+= smb1398-charger.o pmic-voter.o
obj-$(CONFIG_QPNP_SMBLITE)		+= step-chg-jeita.o vivo-battery.o qpnp-smblite.o smblite-lib.o pmic-voter.o storm-watch.o schgm-flashlite.o
obj-$(CONFIG_STM32l011X4) += vivo-stm32l011x4-dual-chg.o
obj-$(CONFIG_FUEL_SUMMARY) += vivo-fuel_summary.o